#!/bin/bash

# 台灣房東越南租客管理系統 - 一鍵部署腳本
# 請按照以下步驟執行

echo "🚀 台灣房東越南租客管理系統 - 部署腳本"
echo "=========================================="
echo ""
echo "📋 系統狀態："
echo "   ✅ 開發完成"
echo "   ✅ 測試通過"
echo "   ✅ 準備部署"
echo ""
echo "⏱️  預計部署時間：10-15分鐘"
echo ""

# 步驟 1：建立 GitHub 倉庫
echo "📝 步驟 1：建立 GitHub 倉庫"
echo "------------------------------------------"
echo "1. 登入 GitHub (https://github.com)"
echo "2. 點擊右上角 '+' → 'New repository'"
echo "3. 設定倉庫資訊："
echo "   - Repository name: taiwan-landlord-vietnam-tenant-system"
echo "   - Description: 台灣房東越南租客管理系統 (Multi-Property Management System Pro v2.0)"
echo "   - Public 或 Private (根據需求選擇)"
echo "   - 不要初始化 README、.gitignore 或 license"
echo "4. 點擊 'Create repository'"
echo ""
read -p "完成後按 Enter 繼續..."

# 步驟 2：推送到 GitHub
echo ""
echo "📝 步驟 2：推送到 GitHub"
echo "------------------------------------------"
echo "請在專案目錄中執行以下命令："
echo ""
echo "cd /home/node/.openclaw/workspace/taiwan-landlord-vietnam-tenant-system"
echo "git remote add origin https://github.com/YOUR_USERNAME/taiwan-landlord-vietnam-tenant-system.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "請將 YOUR_USERNAME 替換為您的 GitHub 用戶名"
echo ""
read -p "完成後按 Enter 繼續..."

# 步驟 3：Vercel 部署
echo ""
echo "📝 步驟 3：Vercel 部署"
echo "------------------------------------------"
echo "1. 登入 Vercel (https://vercel.com)"
echo "2. 點擊 'New Project'"
echo "3. 匯入 GitHub 倉庫："
echo "   - 選擇剛剛建立的倉庫"
echo "   - 點擊 'Import'"
echo "4. 專案設定："
echo "   - Framework Preset: Next.js"
echo "   - Build Command: npm run build"
echo "   - Output Directory: .next"
echo "   - Install Command: npm ci --include=dev"
echo "5. 環境變數（可選）："
echo "   - 參考 .env.example 檔案"
echo "6. 點擊 'Deploy'"
echo ""
echo "⏱️  部署時間：約 3-5 分鐘"
echo ""
read -p "完成後按 Enter 繼續..."

# 步驟 4：測試部署
echo ""
echo "📝 步驟 4：測試部署"
echo "------------------------------------------"
echo "部署完成後，請測試以下功能："
echo ""
echo "1. 訪問您的 Vercel 連結："
echo "   https://taiwan-landlord-vietnam-tenant-system.vercel.app"
echo ""
echo "2. 測試核心功能："
echo "   ✅ 新增物業"
echo "   ✅ 新增房間"
echo "   ✅ 出租房間"
echo "   ✅ 收取租金"
echo "   ✅ 電費計算"
echo "   ✅ 語言切換（中文/越南文）"
echo "   ✅ 資料匯入匯出"
echo ""
echo "3. 確認所有功能正常運作"
echo ""

# 部署完成
echo "🎉 部署完成！"
echo "=========================================="
echo ""
echo "✅ 系統已成功部署！"
echo "📱 訪問連結：https://taiwan-landlord-vietnam-tenant-system.vercel.app"
echo ""
echo "📞 如有問題，請檢查："
echo "   1. GitHub 倉庫權限設定"
echo "   2. Vercel 部署日誌"
echo "   3. 瀏覽器控制台錯誤"
echo ""
echo "🔧 技術支援："
echo "   - 查看 DEPLOYMENT_CHECKLIST.md 獲取詳細指引"
echo "   - 查看 PROJECT_SUMMARY.md 了解技術細節"
echo "   - 執行 scripts/test-deployment.sh 進行本地測試"
echo ""
echo "💾 系統功能："
echo "   - 🏢 多物業管理"
echo "   - 🏠 房間管理"
echo "   - 💰 租金管理"
echo "   - ⚡ 電費計算"
echo "   - 🔧 維修管理"
echo "   - 🌐 多語言支援"
echo "   - 💾 資料管理"
echo ""
echo "🚀 祝您使用愉快！"